lesson 6, home work ex1
evgeniyTagil/HelloWorldProject pull request #12
Opened 2023-04-07 19:52 UTC by evgeniyTagil

2023-04-07 22:10 UTC, evgeniyTagil reviewed
Понятно что я не учитывал то что вместо цифр могут вводится символы) если нужно могу переделать

2023-04-08 07:43 UTC, Pavel-Tsishkevich commented on src/lesson6/homework/CredicCard.java
> +public class CredicCard {
Credic))

2023-04-08 07:44 UTC, Pavel-Tsishkevich commented on src/lesson6/homework/CredicCard.java
> +    private int userGetMoney; //сумма введенная пользователем
Можно просто paymentSum

2023-04-08 07:48 UTC, Pavel-Tsishkevich requested changes
Вообще задумка отличная, только пару методов перетащить надо в мейн класс

2023-04-08 07:48 UTC, Pavel-Tsishkevich commented on src/lesson6/homework/CredicCard.java
> +    public void authorization() {
Смотри, такой метод есть не у карточки, а у автомата, потому что карточка не знает про другие карточки, может только сравнить свой пароль с введённым

2023-04-08 07:48 UTC, Pavel-Tsishkevich commented on src/lesson6/homework/CredicCard.java
> +    public void menu() { //Меню
Это тоже больше для мейн метода подходит и класса с мейном

2023-04-10 19:00 UTC, merged